version: 2

sources:
  - name: silver
    schema: silver
    tables:
      - name: dim_commune
      - name: fact_article
      - name: fact_mention
      - name: fact_mention_nlp_input
        columns:
          - name: mention_id
            tests:
              - not_null
              - unique
              - relationships:
                  arguments:
                    to: source('silver', 'fact_mention')
                    field: mention_id
      - name: fact_mention_nlp_summary
      - name: fact_mention_frame_score
      - name: fact_stereotype_word_counts

  - name: gold
    schema: gold
    tables:
      - name: sample_leaders
